name: Build and Deploy on Push to Main

on:
  push:
    branches: main

# Need ID token write permission to use OIDC
permissions:
  contents: read
  id-token: write
concurrency:
  group: deploy-main
  cancel-in-progress: true
jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04-arm
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::943189351074:role/GitHubActionsTrustPolicy
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: 943189351074
      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mini-fintech-platform
        run: |
          docker build "backend" --platform "linux/arm64" -f "backend/Dockerfile" -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "image_tag=$IMAGE_TAG" 
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: terraform
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color -input=false -var="image_tag=${IMAGE_TAG}"
        working-directory: terraform